[package]
name = "junk"
version = "0.1.0"
authors = ["ESC <youhavethewrong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# syscalls =  "0.1.1" # -- only on Linux